# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


$script = <<SCRIPT
sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
sudo apt-get -q -y update
sudo apt-get -q -y --force-yes install lxc-docker git wget curl
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
  config.vm.box = 'precise64'
  #config.vm.provision "docker",
  #  images: ["ubuntu"]
end

